### ISSUE TITLE
Any Issue or specific task to contribute?

### ISSUE THREAD

**Issue by jarrisondev** [shyynux/i-did-it#1]

**Comment by shyynux** [comment]
This is the current design of the application.
![i-did-it](https://github.com/shyynux/i-did-it/assets/128243259/e5bcc641-c1ab-421e-98d3-f3918f6f807a)

1. You can work on updating home.jsx to look like this. (we are using tailwind css)
2. If you want something to just start with you can make documentation changes to readme or contribution.md.

**Comment by shyynux** [comment]
I have added a couple of issues you can have a look.
